services:
  - type: web
    name: octopus-monitor-site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    healthCheckPath: /healthz
